### ISSUE TITLE
Allow definition of terraform vars when running plan

### ISSUE THREAD

**Issue by jwermuth** [danskespil/gradle-plugin-terraform#6]
e.g. terraform plan -var 'hosts="1"'

**Comment by double16** [comment]
I'd like to use this plugin and I need to use variables. I'd like to work this issue. I'm thinking of both variables and variable files:

tfPlan {
    var 'somevar', 'somevalue'
    var_file file('common.tfvars')
}

Only thing I don't like is both tfApply and tfValidate need the same config. I could also add an extension that tasks can reference:

terraform {
    var 'somevar', 'somevalue'
    var_file file('common.tfvars')
}

Thoughts?

**Comment by jwermuth** [comment]
Hi @double16 . Thanks for considering contribution.

I would go for adding the variables to both commands, and avoid code duplication with inheritance or delegation or something similar.

Why:
In the case of tfPlan and tfApply, the semantics of -var and -var-file is identical. This may not be the case for other options, e.g. -skip (just an imaginary option) may be defined for 2 commands and mean different things. Things that your may want to configure independantly. This can not be done when using an extension to configure without naming the imaginary -skip option so you can tell one from the other in the extension
```
terraform {
   commandA_skip true
  commandB_skip false
}
```
or 
```
terraform {
   commandA {
    skip true
  }
   commandB {
    skip true
  }
}
```
this is doable, but I find it less intuitive
